// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwWCU21d33tZYZIiykb78pvzL-KpJM6-0',
    appId: '1:68490657747:web:9c5f8c5918a15d859b7926',
    messagingSenderId: '68490657747',
    projectId: 'inventoryapp-95c1a',
    authDomain: 'inventoryapp-95c1a.firebaseapp.com',
    storageBucket: 'inventoryapp-95c1a.firebasestorage.app',
    measurementId: 'G-94M90HLC7S',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxnWkdd9brnbBX-KWg4n4QGex_c_EiVM8',
    appId: '1:68490657747:ios:c255cc30c6f628e89b7926',
    messagingSenderId: '68490657747',
    projectId: 'inventoryapp-95c1a',
    storageBucket: 'inventoryapp-95c1a.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxnWkdd9brnbBX-KWg4n4QGex_c_EiVM8',
    appId: '1:68490657747:ios:c255cc30c6f628e89b7926',
    messagingSenderId: '68490657747',
    projectId: 'inventoryapp-95c1a',
    storageBucket: 'inventoryapp-95c1a.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUaSoaehO2aKLb2g3Spqf8c_V5VbhdwyY',
    appId: '1:68490657747:android:d72869fbf8cec01a9b7926',
    messagingSenderId: '68490657747',
    projectId: 'inventoryapp-95c1a',
    storageBucket: 'inventoryapp-95c1a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwWCU21d33tZYZIiykb78pvzL-KpJM6-0',
    appId: '1:68490657747:web:84a3fc1f15681ef79b7926',
    messagingSenderId: '68490657747',
    projectId: 'inventoryapp-95c1a',
    authDomain: 'inventoryapp-95c1a.firebaseapp.com',
    storageBucket: 'inventoryapp-95c1a.firebasestorage.app',
    measurementId: 'G-XN31PB8FG6',
  );

}